app:
  env: local
  serviceName: "go-o11y-base"
  podName: "go-o11y-base-local-1234567890-abcde"
  log:
    pretty: false
    level: debug
    path: ./logs/log
    maxAge: 72h
    rotationTime: 1h

server:
  http:
    port: 8080
    timeout:
      readTimeout: 2s
      readHeaderTimeout: 2s
      writeTimeout: 10s
      idleTimeout: 5s
  grpc:
    port: 8081
    enableReflect: true

observability:
  pprof:
    enabled: false
    port: 6060
    readTimeout: 10s
    writeTimeout: 65s
    idleTimeout: 120s
  otel:
    enabled: false
    endpoint: "localhost:4317" # grpc ep
    sampleRatio: 1.0
  pyroscope:
    enabled: false
    endpoint: "http://localhost:4040"

connections:
  mysql:
    gorm:
      logEnabled: true # 是否啟用 GORM log
      logSlowThreshold: 200ms # 慢查詢閾值
    master:
      host: 127.0.0.1
      port: 3306
      username: root
      password:
      name: go_o11y_base
      maxIdleConns: 20
      maxOpenConns: 20
      connMaxLifetime: 30m
  redis:
    cluster:
      addrs:
        - 127.0.0.1:6379
      username:
      password:
      dialTimeout: 5s
      readTimeout: 3s
      writeTimeout: 3s
      poolSize: 10
      minIdleConns: 2
      maxOpenConns: 10
      connMaxIdleTime: 30s
  kafka:

jwt:
  privateKeyBase64: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUVDb2Q4RzNDeFFtUlBYcWNoR1hjdWc2VldwMktxZDNUMzU4RjUzZjJETzAKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo="
  publicKeyBase64: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQWp1a1dvL3UvSXNwRUx6Z25GS2l5MHdFVTNRK1ZicGQyc3lmblBMWkkxRms9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
  duration: 1000h
  refreshDuration: 1000h
